### ISSUE TITLE
Possible to use with existing InfluxDB and Grafana installation?

### ISSUE THREAD

**Issue by devax** [johanmeiring/mikrocount#1]
Hey,
Just came accross your project and am very interested in it.
In my network, I'm already running an instance of InfluxDB and an instance of Grafana. It would be nice if your script could integrate with the existing installation.
I have tried to use only the mikrocount part of the docker compose file. In addition, I added this section to the service definition: 

> environment:
      - influxdb=192.168.88.2

The IP is the ip of my current InfluxDB host.
Unfortunately, this did not work. The container starts up, but no database has been created on InfluxDB. `docker logs mikrocount` outputs this:

> 2018/07/25 21:25:09 About to process 95 results
2018/07/25 21:25:09 Error:  Post http://influxdb:8086/write?consistency=&db=mikrocount&precision=us&rp=: dial tcp: lookup influxdb on 127.0.0.11:53: no such host

Is there a way I can set it up this way?

Best regards,
Mark

**Comment by devax** [comment]
Oops, I think I just answered my own question. According to the docker compose documentation, this is the correct way to specify additional hosts:
>     extra_hosts:
      - "influxdb:192.168.88.2"
This seems to work, a database has been created and data is being added. Nice!

**Comment by johanmeiring** [comment]
@devax Cool, I'm glad it's working for you :-)
