### ISSUE TITLE
No data in dashboard 

### ISSUE THREAD

**Issue by Nicoraschia** [johanmeiring/mikrocount#3]
Hi, thanks for the contribution, I can't get data from grafana, nothing shows up.

![image](https://user-images.githubusercontent.com/52290963/186197951-fd74596a-a6dc-4a74-8a26-fa1f39d0d640.png)

I check the correct acceso to MK, it Ok.  Any troubleshoting?

**Comment by johanmeiring** [comment]
Hi hi!  Two things I can think of checking:

1. Ensure you've followed the Mikrotik config instructions at https://github.com/johanmeiring/mikrocount#configuring-the-mikrotik-router
2. Make 100% certain that none of your packets are being [fasttracked](https://wiki.mikrotik.com/wiki/Manual:IP/Fasttrack).

**Comment by Nicoraschia** [comment]
Hi @johanmeiring !! Thanks for you fast response. i followed his instructions. 

I was trying to do some debugging.
![image](https://user-images.githubusercontent.com/52290963/186297165-450343f9-2676-404b-8cdd-8cfdafcf3525.png)

And the router correct access
![image](https://user-images.githubusercontent.com/52290963/186297279-443dbd88-ed1b-40a9-aaa5-181b65fc4fe9.png)

---------------------------
LOG
mikrocount_1  | 2022/08/24 19:40:03 About to process 1577 results
mikrocount_1  | 2022/08/24 19:40:03 Weirdness! From: 10.20.1.33 :: To: 18.65.48.42
----------------------------
INFLUX only internal folder.
>pwd
/var/lib/influxdb/data
>  ls -a
.          ..         _internal

**Comment by johanmeiring** [comment]
So, to confirm:

1. Your router is at 192.168.41.1, and you have additional subnets at 192.168.0.x and 192.168.42.x (possibly more), thus a CIDR of 192.168.0.0/16 is correct?
2. Did you double-check that your Mikrotik is not applying fasttrack to packets?

**Comment by frams** [comment]
any solutions? i have the same issue, I'm sure 100% that my router is not using Fastrack.

Thanks

**Comment by Nicoraschia** [comment]
@frams https://github.com/ncareau/Mikro-Watch  it work

**Comment by frams** [comment]
> @frams https://github.com/ncareau/Mikro-Watch it work

thanks.

**Comment by johanmeiring** [comment]
The above looks like a good and decently maintained solution.  I might end up archiving this repo and pointing people to it instead.
